### ISSUE TITLE
Error Occurred while resizing the video

### ISSUE THREAD

**Issue by maliqhammad** [techgnious/IVCompressor#4]
io.github.techgnious.exception.VideoException: Error Occurred while resizing the video
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at io.github.techgnious.IVCompressor.encodeVideo(IVCompressor.java:510)
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at io.github.techgnious.IVCompressor.reduceVideoSize(IVCompressor.java:269)
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at com.krunal.example.MainActivity.onActivityResult(MainActivity.java:247)
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:8408)
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:5318)
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5366)
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2021-12-09 11:44:07.982 26426-26426/com.krunal.example W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2021-12-09 11:44:07.983 26426-26426/com.krunal.example W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2203)
2021-12-09 11:44:07.983 26426-26426/com.krunal.example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-12-09 11:44:07.983 26426-26426/com.krunal.example W/System.err:     at android.os.Looper.loop(Looper.java:268)
2021-12-09 11:44:07.983 26426-26426/com.krunal.example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8019)
2021-12-09 11:44:07.983 26426-26426/com.krunal.example W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-09 11:44:07.983 26426-26426/com.krunal.example W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
2021-12-09 11:44:07.983 26426-26426/com.krunal.example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

**Comment by v22lel** [comment]
Same for me. The problem is, that th error doesnt tell what specifically is wrong - just that it is.

**Comment by govind2517** [comment]
Possibly the original file may have some issue, like extension mismatch or width or height in odd number.
I tried to make them in valid even numbers.
If you resizing video like from 4K to HD dimension make sure that aspect ratio is maintained.
